version: "3.6"
services:
  unciv:
    build: .
    container_name: unciv
    ports:
      - "6901:6901"
      - "5901:5901"
    command: /home/headless/Desktop/Unciv.sh
    volumes:
      unciv-data: /home/headless/.local/share/Unciv

volumes:
  unciv-data:
