site_name: Unciv
docs_dir: docs/
theme:
  name: material
  language: en
  logo: assets/Icon.png
  favicon: assets/favicon.png

  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/github

repo_name: yairm210/unciv
repo_url: https://github.com/yairm210/unciv
site_url: https://yairm210.github.io/Unciv

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets

plugins:
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: false
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: af
          name: Afrikaans
          build: true
        - locale: bn
          name: বাংলা
          build: true
        - locale: be
          name: Беларуская
          build: true
        - locale: bs
          name: Bosanski
          build: true
        - locale: pt-BR
          name: Português (Brasil)
          build: true
        - locale: bg
          name: Български
          build: true
        - locale: ca
          name: Català
          build: true
        - locale: hr
          name: Hrvatski
          build: true
        - locale: cs
          name: Čeština
          build: true
        - locale: nl
          name: Nederlands
          build: true
        - locale: tl
          name: Filipino
          build: true
        - locale: fi
          name: Suomi
          build: true
        - locale: fr
          name: Français
          build: true
        - locale: gl
          name: Galego
          build: true
        - locale: de
          name: Deutsch
          build: true
        - locale: el
          name: Ελληνικά
          build: true
        - locale: hi
          name: हिन्दी
          build: true
        - locale: hu
          name: Magyar
          build: true
        - locale: id
          name: Bahasa Indonesia
          build: true
        - locale: it
          name: Italiano
          build: true
        - locale: ja
          name: 日本語
          build: true
        - locale: ko
          name: 한국어
          build: true
        - locale: la
          name: Latina
          build: true
        - locale: lt
          name: Lietuvių
          build: true
        - locale: ms
          name: Bahasa Melayu
          build: true
        - locale: mt
          name: Malti
          build: true
        - locale: "no"
          name: Norsk
          build: true
        - locale: pl
          name: Polski
          build: true
        - locale: pt
          name: Português
          build: true
        - locale: ro
          name: Română
          build: true
        - locale: ru
          name: Русский
          build: true
        - locale: zh
          name: 简体中文
          build: true
        - locale: es
          name: Español
          build: true
        - locale: sv
          name: Svenska
          build: true
        - locale: th
          name: ไทย
          build: true
        - locale: zh-TW
          name: 繁體中文
          build: true
        - locale: tr
          name: Türkçe
          build: true
        - locale: uk
          name: Українська
          build: true
        - locale: vi
          name: Tiếng Việt
          build: true
        - locale: zu
          name: isiZulu
          build: true
  - search
