name: 'Close stale issues and PRs'
on:
  workflow_dispatch: 
  schedule:
    - cron: '13 3 * * *'
 
    
permissions:
  issues: write
  pull-requests: write
  
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because it has been open 90 days with no activity. Remove stale label or comment or this will be closed in 15 days.'
          stale-pr-message: 'This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 10 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 5 days with no activity.'
          close-pr-message: 'This PR was closed because it has been stalled for 10 days with no activity.'
          days-before-issue-stale: 90
          days-before-pr-stale: 45
          days-before-issue-close: 15
          days-before-pr-close: 10
          exempt-issue-labels: 'Will not stale'
          operations-per-run: 2500
